deudas/deudas/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'deudas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('front.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT}))

deudas/front/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from front import views 

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',views.Login.as_view(), name="login"),
    url(r'^list/$',views.List.as_view(), name="list"),
    url(r'^logout/$',views.LogOut.as_view(), name="logout"),
    url(r'^add/cliente$',views.addCliente.as_view(), name="add-cliente"),
    url(r'^add/glosa/$',views.addGlosa.as_view(), name="add-glosa"),
    url(r'^add/cobro$',views.addCobro.as_view(), name="add-cobro"),
    url(r'^add/abono$',views.addAbono.as_view(), name="add-abono"),
    url(r'^edit/cliente/$',views.editCliente.as_view(), name="edit-cliente"),
    url(r'^delete/cliente/$',views.deleteCliente.as_view(), name="delete-cliente"),
    url(r'^delete/ingreso/$',views.deleteIngreso.as_view(), name="delete-ingreso"),
    url(r'^filter/$',views.filter.as_view(), name="filter"),
    url(r'^excel/(?P<interval>.+)/(?P<fecha>.+)/$',views.excel.as_view(), name="excel"),
    url(r'^cartas/cartas.pdf$',views.cartas.as_view(), name="cartas"),
    url(r'^cartas/(?P<id>\d+)$',views.cartas.as_view(), name="carta"),
    url(r'^mensualidad/$',views.aplicarMensualidad.as_view(), name="mensualidad"),
    url(r'^createUser/$',views.createUser.as_view(), name="create-user"),
    url(r'^changePassword/$',views.changePassword.as_view(), name="change-password"),

    url(r'^cliente/(?P<id>\d+)$',views.cliente.as_view(), name="cliente"),
    url(r'^load/log',views.loadLog.as_view(), name="load-log"),
    url(r'^config/',views.config.as_view(), name="config"),
)

deudas/report/urls.py
# -*- coding: utf-8 -*-

import datetime, imp
from django.conf.urls.defaults import *
from django.conf import settings
from reports.views import *
from django.views.generic.date_based import archive_year
from django.contrib.admin.models import LogEntry
from django.utils.importlib import import_module

queryset    = LogEntry.objects.all()
report_conf = settings.REPORT_CONF
report_conf['title'] = 'Admin action log (%d total)' % len(queryset)

urlpatterns = patterns('',
    url(r'^actions/$', archive_year, {
        'year':             datetime.datetime.now().year,
        'date_field':       'action_time',
        'make_object_list': True,
        'queryset':         queryset,
        'template_name':    'report/actions.html',
        'extra_context':    settings.REPORT_CONF,
    },name='reports-actions'),
) 

for app in settings.INSTALLED_APPS:
    try:
        app_path = import_module(app).__path__
    except AttributeError:
        continue
    try:
        imp.find_module('report_urls', app_path)
    except ImportError:
        continue
        
    urlpatterns += patterns('',
        (r'^%s/' % app.split('.')[-1], include('%s.report_urls' % app)),
    )

deudas/front/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.

class Cliente(models.Model):
	rut = models.CharField(max_length=12, verbose_name="RUT")
	nombre = models.CharField(max_length=1000, verbose_name="Nombre")
	tipo_opciones = (
        ('natural', u"Persona Natural"), 
        ('sociedad', u"Sociedad"))
	tipo = models.CharField(max_length=20, choices=tipo_opciones, default=tipo_opciones[0][0], verbose_name=u"Tipo")
	duenio = models.CharField(max_length=1000, verbose_name=u"Dueño", blank=True)
	activo_opciones = (
        ('activo', u"Activo"), 
        ('no-activo', u"No Activo"))
	activo = models.CharField(max_length=20, choices=activo_opciones, default=activo_opciones[0][0], verbose_name=u"Activo")
	mensualidad = models.IntegerField(verbose_name=u"Mensualidad", blank=True, null=True)

	def __unicode__(self):
		return self.nombre

class Glosa(models.Model):
	nombre = models.CharField(max_length=500, verbose_name=u"Nombre")
	detalle = models.TextField(verbose_name=u"Detalle")

	def __unicode__(self):
		return '%s' % self.nombre

class Ingreso(models.Model):
	fecha = models.DateTimeField(verbose_name=u"Fecha")
	tipo_opciones = (
        ('deuda', u"Deuda"), 
        ('boleta', u"Boleta"))
	tipo = models.CharField(max_length=20, choices=tipo_opciones, default=tipo_opciones[0][0], verbose_name=u"Tipo")
	valor = models.IntegerField(verbose_name=u"Valor")
	numero = models.IntegerField(verbose_name=u"Numero de Boleta", blank=True)
	glosa = models.ForeignKey(Glosa, default=2)
	cliente = models.ForeignKey(Cliente)

	def __unicode__(self):
		try:
			return self.cliente.nombre + " - " + self.glosa.nombre
		except:
			try:
				return self.glosa.nombre
			except:
				return self.cliente.nombre

class Config(models.Model):
	cartaPerPage = models.IntegerField(verbose_name=u"Cartas por Página", blank=True, null=True)
	cerosOnXlsBody = models.BooleanField(verbose_name=u"Mostrar Ceros en el Detalle del archivo Excel", default=False)
	cerosOnXlsFooter = models.BooleanField(verbose_name=u"Mostrar Ceros en el Total del archivo Excel", default=True)
	activarMensualidad = models.BooleanField(verbose_name=u"Activar cobro Automático de Mensualidad", default=True )

deudas/templates/auth.html
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
		<link href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
		<!-- Javascript -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	</head>
	<body>
		<div class="container">
			<div class="well">
				<form action="{% url "login" %}" method=POST>
					{% csrf_token %}
					{{form.as_p}}
					<button class="btn btn-primary"> Entrar </button>
				</form>
			</div>
		</div>
	</body>
</html>

deudas/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon"  type="image/x-icon" href="{% static 'favicon.png' %}"/>
		<title>Sistema de Balance - Estudio Contable Allison & Ltda</title>

		<!-- CSS -->
		<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
		<link href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
		<link href="//cdn.datatables.net/1.10.1/css/jquery.dataTables.css" rel="stylesheet"/>
		<link rel="stylesheet" href="{% static 'js/datepicker/css/datepicker.css'%}" />
		<link rel="stylesheet" type="text/css" href={% static "css/stylesheet.css" %} media="screen" />

		<!-- Javascript -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
		<script src="//cdn.datatables.net/1.10.1/js/jquery.dataTables.js"></script>
		<script src="{% static 'js/datepicker/js/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
				  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				    <span class="sr-only">Toggle navigation</span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				  </button>
				  <a class="navbar-brand" href="{% url 'list' %}">Sistema de Balance</a>
				</div>
				 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				  <ul class="nav navbar-nav navbar-right">
				  	<li><a href="{% url 'config' %}">Configuración</a></li>
				  	<li><a href="{% url 'create-user' %}">Crear Usuario</a></li>
				  	<li><a href="{% url 'change-password' %}">Cambiar Contraseña</a></li>
				  	<li><a href="{% url 'logout' %}">Log Out</a></li>
				  </ul>
				 </div>
			</div><!-- /.container-fluid -->
		</nav>
		<div class="container">
			<div class ="row">
				<div class="col-md-12">
				{% block body %}
				{% endblock %}
				</div>
			</div>
		</div>
		<div class="loading">
			<img src="http://i.stack.imgur.com/MnyxU.gif">
		</div>
	</body>
	{% block modal %}

	{% endblock %}
</html>

deudas/templates/carta.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Sistema de Balance - Estudio Contable Allison & Ltda</title>

		<!-- CSS -->
		<link rel="stylesheet" type="text/css" href={% static "css/print.css" %} />
		<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script>
		$(window).on("load", function(){window.print()});
		</script>
	</head>
	<body>
		<div class="carta">
		{% for client in clients %}
			<div class="row">
				
			</div>
			<div class="row">
				<div class="col-md-6 center uppercase">
					<p>John Allison Lopez<br/>
					Colegio de Contadores Nº 12824-9<br/>
					Fonos: 222151-227453</p>
				</div>
				<div class="col-md-3 center">
					<p>La Calera</p>
				</div>
				<div class="col-md-3 center uppercase">
					<p>{% now "F \d\e\l Y" %}</p>
				</div>
			</div>
			<div class="row">
				<p>Estimado Señor(a):</p>
				<p class="indent">Le adjunto un detalle de mis Honorarios, que le agradecería cancelar a su más pronta conveniencia</p>
			</div>
			<div class="row">
				<table class="no-border">
					<tr>
						<td>{{client.1.0}} ({{ lastMonth|date:"F" }})</td>
						<td>{{client.1.1}}</td>
					</tr>
					<tr>
						<td>{{client.2.0}}</td>
						<td>{{client.2.1}}</td>
					</tr>
					{% for glosa in client.3 %}
						{% if glosa.1 > 0 %}
							<tr>
								<td>{{glosa.0}}</td>
								<td>{{glosa.1}}</td>
							</tr>
						{% endif %}
					{% endfor %}
					<tr>
						<td>Total</td>
						<td>{{client.4}}</td>
					</tr>
				</table>
				<p class="indent">Les saluda atentamente:</p>
			</div>
			<div class="row">
				<p> Presente. - </p>
			</div>
			<div class="row">
				<p class="little"> {{client.0}}</p>
			</div>
			{% if forloop.counter|divisibleby:cartaPerPage %}
				</div>
				<div class="carta">
			{% endif %}
		{% endfor %}
	</body>
</html>

deudas/templates/cliente.html
{% extends "base.html" %}
{% block body %}
<h1>
	{% if prev %}
	<a class="btn btn-default" href='{% url "cliente" id=prev %}'>
		<span class="glyphicon glyphicon-arrow-left"> </span>
	</a> 
	{% endif %}
	{{cliente.nombre}}
	{% if next %}
		<a class="btn btn-default" href='{% url "cliente" id=next %}'>
			<span class="glyphicon glyphicon-arrow-right"> </span>
		</a> 
	{% endif %}
</h1>
<div class="row">
	<div class="col-md-3">
		<strong>RUT:</strong> {{cliente.rut}}
	</div>
	<div class="col-md-3">
		<strong>Tipo:</strong> {{cliente.get_tipo_display}}
	</div>
	<div class="col-md-3">
		<strong>Dueño:</strong> {{cliente.duenio}}
	</div>
	<div class="col-md-3">
		<strong>Activo:</strong> {{cliente.activo}}
	</div>
</div>
<p class="lead col-md-6">
	<strong>Mensualidad:</strong> <span class="label label-primary">$M{% if cliente.mensualidad == None %} 0 {% else %} {{cliente.mensualidad}}{% endif %}</span>
</p>
<p class="lead col-md-6">
	<strong>Total:</strong> <span class="label {% if balance > 0 %}label-danger{%else%}label-primary{%endif%}">$M{{balance}}</span>
</p>
<div class="row">
  <button class="btn btn-primary" data-toggle="modal" data-target="#agregarAbono" >
  	Agregar Abono
  	<span class="glyphicon glyphicon-minus"></span>
  </button>
  <button class="btn btn-danger" data-toggle="modal" data-target="#agregarCobro" >
  	Agregar Cobro
  	<span class="glyphicon glyphicon-plus"></span>
  </button>
  <button class="btn btn-success" data-toggle="modal" data-target="#editCliente">
  	Editar Cliente
  	<span class="glyphicon glyphicon-edit"></span>
  </button>
</div>
<div class="row">
  <div class="col-md-2 pull-left">
    <select class="form-control change-dates">
      {% for date in dates %}
        <option value="{{date}}">{{date}}</option>
      {% endfor %}
    </select>
  </div>
  <a href={%url "carta" cliente.pk %} target="_blank" class="btn btn-danger link-letter" id="exportPDF">
    Imprimir Carta
    <span class="glyphicon glyphicon-share"></span>
  </a>
</div>
<!-- Nav tabs -->
<div class="row">
<div class="col-md-5">
  <div class="col-md-4">
    <input type="text" class="form-control datepicker interval-log" id="desde" value="{{dateBegining}}"/>
  </div>
  <div class="col-md-4">
    <input type="text" class="form-control datepicker interval-log" id="a" value="{{dateEnd}}"/>
  </div>
  <button class="filter-date btn btn-warning"> Aplicar Fechas </button>
</div>
<div class="col-md-7">
  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#completo" role="tab" data-toggle="tab">Log Completo</a></li>
    <li><a href="#abono" role="tab" data-toggle="tab">Log Abono</a></li>
    <li><a href="#cobro" role="tab" data-toggle="tab">Log Cobro</a></li>
  </ul>
</div>
</div>

<!-- Tab panes -->
<div id="tab-container">
{% include 'tab.html' %}
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id="editCliente">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Editar Cliente</h4>
      </div>
      <form action="{% url 'add-cliente'%}"  method="POST">
      		{% csrf_token %}
	      <div class="modal-body">
	        {{formCliente.as_p}}
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="agregarCobro">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Cobro</h4>
      </div>
      <form action="{% url 'add-cobro'%}"  method="POST">
      		{% csrf_token %}
      		<input type="hidden" name="cliente_pk" class="cliente_pk" value="{{cliente.pk}}"/>
      		<input type="hidden" name="where" value="cliente"/>
	      <div class="modal-body">
	      {{ form.errors }}
			{{ form.non_field_errors }}
	        {{formCobro.as_p}}
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="agregarAbono">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Abono</h4>
      </div>
      <form action="{% url 'add-abono'%}"  method="POST">
      		{% csrf_token %}
      		<input type="hidden" name="cliente_pk" class="cliente_pk" value="{{cliente.pk}}"/>
      		<input type="hidden" name="where" value="cliente"/>
	      <div class="modal-body">
	        {{formAbono.as_p}}
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="deleteIngreso">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Borrar Ingreso</h4>
      </div>
      <form action="{% url 'delete-ingreso'%}"  method="POST">
          {% csrf_token %}
          <input type="hidden" name="cliente_pk" class="cliente_pk" value="{{cliente.pk}}"/>
          <input type="hidden" name="pk" class="pk" value="{{cliente.pk}}"/>
        <div class="modal-body">
          Está seguro que quiere realizar ésta operación?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
          <button type="submit" class="btn btn-primary">Sí</button>
        </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

deudas/templates/creation.html
{% extends "base.html" %}
{% block body %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="btn btn-primary" />
</form>
{% endblock %}

deudas/templates/form.html
{{form.as_p}}

deudas/templates/lista.html
{% extends "base.html" %}
{% block body %}
  <form action='{%url "cartas" %}' id="exportPDF" method="GET">
    {% csrf_token %}
    <button  class="btn btn-danger">
      Imprimir Cartas
      <span class="glyphicon glyphicon-share"></span>
    </button>
  </form>
<p>
	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#agregarCliente">
		Agregar nuevo Cliente
	</button>
	<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#agregarGlosa">
		Agregar nueva Glosa
	</button>
  <a href={%url "excel" "m" ahora %} class="btn btn-success" id="exportExcel">
    Exportar a Excel
    <span class="glyphicon glyphicon-share"></span>
  </a>
</p>

   <div class="checkbox col-md-12">
    <label>
      <input type="checkbox" id="activo"  checked="checked"> Incluir no Activos
    </label>
  </div>
<div class="col-md-6">
	<select class="form-control" id="filter">
		<option value="all">--</option>
		<option value="natural">Persona Natural</option>
    <option value="sociedades">Sociedades</option>
    <option value="no">Sociedades sin Dueño Seteado</option>
		{% for duenio in duenios %}
			{% if duenio.0 != ""  %}
				<option value="{{duenio.0}}">{{duenio.0|safe}}</option>
			{% endif %}
		{% endfor %}
	</select>
</div>
<div class="col-md-3">
  <select class="form-control col-md-6" id="interval">
    <option value="mensual">Mensual:</option>
    <option value="anual">Anual:</option>
  </select>
</div>
<div class="col-md-3" id="dateContainer">
  <select class="form-control col-md-6" id="date">
    {% for date in dates %}
      <option value="{{date}}">{{date}}</option>
    {% endfor %}
  </select>
</div>
<div class="col-md-3" id="yearContainer">
  <select class="form-control col-md-6" id="year">
    {% for year in years %}
      <option value="{{year}}">{{year}}</option>
    {% endfor %}
  </select>
</div>

<div class="data-table">
{% include 'table.html' %}
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id="agregarCliente">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Agregar Nuevo Cliente</h4>
      </div>
      <form action="{% url 'add-cliente'%}"  method="POST">
      		{% csrf_token %}
	      <div class="modal-body">
	        {{formCliente.as_p}}
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="agregarGlosa">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Editar Glosa</h4>
      </div>
      <form action="{% url 'add-glosa'%}"  method="POST">
      		{% csrf_token %}
	      <div class="modal-body">
          <select id="selectGlosa" name="selectGlosa" class="form-control">
           <option value="new">Agregar Nueva Glosa </option>
           {% for glosa in listGlosa %}
            <option value="{{glosa.pk}}">{{glosa.nombre}}</option>
           {% endfor %}
          </select>
          <div class="whereFormGoesGlosa">
	         {{formGlosa.as_p}}
          </div>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="agregarCobro">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Cobro</h4>
      </div>
      <form action="{% url 'add-cobro'%}"  method="POST">
      		{% csrf_token %}
      		<input type="hidden" name="cliente_pk" class="cliente_pk" value=""/>
	      <div class="modal-body">
	      {{ form.errors }}
			{{ form.non_field_errors }}
	        {{formCobro.as_p}}
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="agregarAbono">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Abono</h4>
      </div>
      <form action="{% url 'add-abono'%}"  method="POST">
      		{% csrf_token %}
      		<input type="hidden" name="cliente_pk" class="cliente_pk" value=""/>
	      <div class="modal-body">
	        {{formAbono.as_p}}
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="editCliente">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Editar Cliente</h4>
      </div>
      <form action="{% url 'edit-cliente'%}"  method="POST">
      		{% csrf_token %}
      		<input type="hidden" name="cliente_pk" class="cliente_pk" value=""/>
	      <div class="modal-body">
	      </div>
	      <div class="modal-footer">
          <a class="btn btn-danger" id="deleteClient">Borrar</a>
	        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
	        <button type="submit" class="btn btn-primary">Guardar</button>
	      </div>
      </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}